### ISSUE TITLE
Release 1.0.4

### ISSUE THREAD

**Issue by heiko-braun** [wildfly/jandex-maven-plugin#10]
Can we get a release of 1.0.4 once the changes in #9 are included?

**Comment by jdcasey** [comment]
I have it staged on jboss.org Nexus, but due to some permission problem I haven't been able to promote it yet (it's closed and sitting there). The URL is:

https://repository.jboss.org/nexus/content/repositories/jboss_releases_staging_profile-7825

If you have access, could you give it a quick kick in the pants? :smile:

**Comment by heiko-braun** [comment]
Thanks @jdcasey . I've released it. I think it should appear on central any time soon.
